imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%_test"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
security:
    firewalls:
        # replace 'main' by the name of your own firewall
        main:
            http_basic: ~